services:
  - type: web
    name: fullstack-backend
    env: python
    buildCommand: |
      mkdir -p data
      pip install -r app/requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        value: '["https://dashflow-r0upi26x3-eswar133s-projects.vercel.app", "http://localhost:3000"]'
      - key: PYTHONPATH
        value: /opt/render/project/src/backend/app
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 