services:
  - type: web
    name: fullstack-backend
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        value: '["https://cosmic-valkyrie-cc6cde.netlify.app"]'
      - key: PYTHONPATH
        value: /opt/render/project/src/backend/app 